backend:
  name: github
  repo: strelitziatrio/strelitziatrio
  branch: main # or master

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
